name: app-dashboard

on:
  workflow_dispatch:
  
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '5 0 * * *'

jobs:
  app-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: |
          pip3 install -r requirments.txt

      - name: Run report
        run: |
          python3 generate_dashboard.py ${{ steps.app-token.outputs.token }}
      
      - name: Push new report
        run: |
          if [ -n "$(git status --porcelain)" ]; then
          {
            git status
            echo "================================="
            
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update new report!"
            git push origin $GITHUB_REF

            echo "View new report at: https://siliconlabs-massmarket.github.io/sample-app"
          }
          else
            echo "No changes";
          fi        
